### ISSUE TITLE
Docker: standard_init_linux.go:211: exec user process caused “no such file or directory”

### ISSUE THREAD

**Issue by laguten** [sku4/alice-checklist#1]
Возникает такая ошибка в результате запуска проекта. Устранить пока не удалось. Возможно, причина в отсутствии .env файла?

![Image 2022-05-26 at 5 05 17 PM](https://user-images.githubusercontent.com/10452157/170518523-fdba1664-de91-4f56-be9f-a3b49fcb7b09.jpeg)

**Comment by sku4** [comment]
Да, нужно создать пустой .env файл

**Comment by laguten** [comment]
Да, конечно, два файла конфигов и пустой .env добавил. Приведенный ранее результат на скриншоте именно после всех этих добавлений.

**Comment by laguten** [comment]
Скрытые файлы (включая пустой .env) не попали в выдачу команды tree:

[~/alice-checklist] [master] [default@oci-2] $> tree
.
├── cmd
│   └── main.go
├── configs
│   ├── config.go
│   ├── config.yml
│   └── googlekeep
│       ├── config.yml
│       └── keep.google.com.har
├── db
│   └── cache.db
├── docker-compose.yml
├── Dockerfile
├── Dockerfile-local
├── docs
│   ├── docs.go
│   ├── swagger.json
│   └── swagger.yaml
├── go.mod
├── go.sum
├── internal
│   ├── handler
│   │   ├── alice.go
│   │   ├── alice_test
│   │   │   └── list.json
│   │   ├── alice_test.go
│   │   ├── handler.go
│   │   └── response.go
│   ├── repository
│   │   ├── googlekeep
│   │   │   └── checklist.go
│   │   ├── mocks
│   │   │   └── repository.go
│   │   ├── notify
│   │   │   └── notify.go
│   │   └── repository.go
│   └── service
│       ├── alice
│       │   ├── alice.go
│       │   ├── alice_test.go
│       │   ├── mocks
│       │   │   ├── alice.go
│       │   │   └── recognize.go
│       │   ├── recognize.go
│       │   └── recognize_test.go
│       ├── mocks
│       │   └── service.go
│       └── service.go
├── lang
│   ├── json
│   │   ├── message.go
│   │   └── ru.json
│   └── message.go
├── Makefile
├── models
│   ├── alice
│   │   ├── channel
│   │   │   └── channel.go
│   │   ├── request.go
│   │   └── response.go
│   └── googlekeep
│       ├── request.go
│       └── response.go
├── pkg
│   ├── boltdb
│   │   ├── cache.go
│   │   ├── errors.go
│   │   ├── mocks
│   │   │   └── storage.go
│   │   ├── node.go
│   │   ├── node_test.go
│   │   └── storage.go
│   └── googlekeep
│       └── client.go
├── README.md
├── README_RU.md
└── server.go

+ скриншот:
![2022-06-01_10_57_17](https://user-images.githubusercontent.com/10452157/171367401-9dde31a7-69fe-4584-8e4d-a4318356f7e3.png)

**Comment by sku4** [comment]
Файлы keep.google.com.har и config.yml должны быть внутри /configs/googlekeep/

**Comment by laguten** [comment]
Они там и находятся. Копипаст текста почему-то исказил отступы. В действительности так: 
![2022-06-02_11_31_44](https://user-images.githubusercontent.com/10452157/171601382-8b05e9ea-f7cf-4da0-8c8b-7a4762f2aad7.png)

Файл же ./configs/config.yml  здесь и находился с оригинальным содержимым:
![2022-06-02_11_38_03](https://user-images.githubusercontent.com/10452157/171601989-3a426977-1fc3-4974-a040-a24c541c9e38.png)

**Comment by sku4** [comment]
Какое содержимое файла ./configs/googlekeep/config.yml?

**Comment by laguten** [comment]
> Какое содержимое файла ./configs/googlekeep/config.yml?

noteRootId: "1570115769974.424303459"

**Comment by sku4** [comment]
Вроде все норм, сложно сказать какого именно файла не находит, пробовал вчистую запускать:

1. git clone
2. добавил .env, ./configs/googlekeep/config.yml и ./configs/googlekeep/keep.google.com.har
3. выполнил make run и все поднялось

**Comment by Algorithm0** [comment]
Я испытываю ту же проблему у себя.
```
├── .bin
│   └── app
├── cmd
│   └── main.go
├── configs
│   ├── config.go
│   ├── config.yml
│   └── googlekeep
│       ├── config.yml
│       ├── .gitignore
│       └── keep.google.com.har
├── db
├── docker-compose.yml
├── Dockerfile
├── Dockerfile-local
├── docs
│   ├── docs.go
│   ├── swagger.json
│   └── swagger.yaml
├── .env
├── .git
│   ├── branches
│   ├── config
│   ├── description
│   ├── HEAD
│   ├── hooks
│   │   ├── applypatch-msg.sample
│   │   ├── commit-msg.sample
│   │   ├── fsmonitor-watchman.sample
│   │   ├── post-update.sample
│   │   ├── pre-applypatch.sample
│   │   ├── pre-commit.sample
│   │   ├── pre-merge-commit.sample
│   │   ├── prepare-commit-msg.sample
│   │   ├── pre-push.sample
│   │   ├── pre-rebase.sample
│   │   ├── pre-receive.sample
│   │   ├── push-to-checkout.sample
│   │   └── update.sample
│   ├── index
│   ├── info
│   │   └── exclude
│   ├── logs
│   │   ├── HEAD
│   │   └── refs
│   │       ├── heads
│   │       │   └── master
│   │       └── remotes
│   │           └── origin
│   │               └── HEAD
│   ├── objects
│   │   ├── info
│   │   └── pack
│   │       ├── pack-ee06c1d7d69239e62f3eb0e2632dd5c5ba89bff5.idx
│   │       └── pack-ee06c1d7d69239e62f3eb0e2632dd5c5ba89bff5.pack
│   ├── packed-refs
│   └── refs
│       ├── heads
│       │   └── master
│       ├── remotes
│       │   └── origin
│       │       └── HEAD
│       └── tags
├── .github
│   ├── images
│   │   ├── 1652480631785.jpg
│   │   └── 1652481194651.jpg
│   └── workflows
│       └── go.yml
├── .gitignore
├── go.mod
├── go.sum
├── internal
│   ├── handler
│   │   ├── alice.go
│   │   ├── alice_test
│   │   │   └── list.json
│   │   ├── alice_test.go
│   │   ├── handler.go
│   │   └── response.go
│   ├── repository
│   │   ├── googlekeep
│   │   │   └── checklist.go
│   │   ├── mocks
│   │   │   └── repository.go
│   │   ├── notify
│   │   │   └── notify.go
│   │   └── repository.go
│   └── service
│       ├── alice
│       │   ├── alice.go
│       │   ├── alice_test.go
│       │   ├── mocks
│       │   │   ├── alice.go
│       │   │   └── recognize.go
│       │   ├── recognize.go
│       │   └── recognize_test.go
│       ├── mocks
│       │   └── service.go
│       └── service.go
├── lang
│   ├── json
│   │   ├── message.go
│   │   └── ru.json
│   └── message.go
├── Makefile
├── models
│   ├── alice
│   │   ├── channel
│   │   │   └── channel.go
│   │   ├── request.go
│   │   └── response.go
│   └── googlekeep
│       ├── request.go
│       └── response.go
├── pkg
│   ├── boltdb
│   │   ├── cache.go
│   │   ├── errors.go
│   │   ├── mocks
│   │   │   └── storage.go
│   │   ├── node.go
│   │   ├── node_test.go
│   │   └── storage.go
│   └── googlekeep
│       └── client.go
├── README.md
├── README_RU.md
└── server.go

48 directories, 82 files

**Comment by sku4** [comment]
> Большое спасибо за Вашу работу!
> 
> Тем не менее я испытываю ту же проблему у себя.
> Может, я где-то не там создал файл `.env`? Можете ли Вы показать Ваш вывод `three -a`?

Нашел ошибку, не хватало пустого каталога db для хранения кеша, поправил в последнем коммите, просьба проверить

**Comment by Algorithm0** [comment]
> > Большое спасибо за Вашу работу!
> > Тем не менее я испытываю ту же проблему у себя.
> > Может, я где-то не там создал файл `.env`? Можете ли Вы показать Ваш вывод `three -a`?
> > @Algorithm0
> > Нашел ошибку, не хватало пустого каталога db для хранения кеша, поправил в последнем коммите, просьба проверить

Спасибо, что быстро отозвались! К сожалению, это мне не помогло:
```
pi@raspberrypi:~/Projects/alice-checklist $ make run
swag init -g ./cmd/main.go
2023/10/17 20:52:47 Generate swagger docs....
2023/10/17 20:52:47 Generate general API Info, search dir:./
2023/10/17 20:52:47 Generating alice.Request
2023/10/17 20:52:47 Generating alice.Meta
2023/10/17 20:52:47 Generating alice.Session
2023/10/17 20:52:47 Generating alice.ReqData
2023/10/17 20:52:47 Generating alice.Intent
2023/10/17 20:52:47 Generating alice.Slot
2023/10/17 20:52:47 Generating alice.State
2023/10/17 20:52:47 Generating alice.Response
2023/10/17 20:52:47 Generating alice.RespData
2023/10/17 20:52:47 Generating handler.errorResponse
2023/10/17 20:52:47 create docs.go at docs/docs.go
2023/10/17 20:52:47 create swagger.json at docs/swagger.json
2023/10/17 20:52:47 create swagger.yaml at docs/swagger.yaml
go build -o ./.bin/app ./cmd/main.go
docker-compose up --remove-orphans --build server
Building server
[+] Building 2.6s (11/11) FINISHED                                                                       docker:default
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load build definition from Dockerfile-local                                                         0.0s
 => => transferring dockerfile: 249B                                                                               0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                   1.2s
 => [internal] load build context                                                                                  1.3s
 => => transferring context: 38.52MB                                                                               1.3s
 => [1/6] FROM docker.io/library/alpine:latest@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc8  0.0s
 => CACHED [2/6] RUN apk --no-cache add ca-certificates                                                            0.0s
 => CACHED [3/6] WORKDIR /root/                                                                                    0.0s
 => CACHED [4/6] COPY ./.bin/app .                                                                                 0.0s
 => CACHED [5/6] COPY ./configs/config.yml ./configs/config.yml                                                    0.0s
 => CACHED [6/6] COPY ./lang/json/*.json ./lang/json/                                                              0.0s
 => exporting to image                                                                                             0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:b2e6f3e75adbc9eb8bd97357961234a3e1400eac597805a6db17ce6615404a72                       0.0s
 => => naming to docker.io/library/alice-checklist                                                                 0.0s
Creating alice ... done
Attaching to alice
alice     | exec ./app: no such file or directory
alice exited with code 1
pi@raspberrypi:~/Projects/alice-checklist $ git rev-parse HEAD
a58ea97e5fc767e3d48aefcceab7409c467a255e
```

**Comment by sku4** [comment]
@Algorithm0 запускается ли сервис через `go run ./cmd/main.go` ?
С последним коммитом подтянулась ли папка db?
Проверьте прокидывает ли docker compose [монтируемые папки](https://github.com/sku4/alice-checklist/blob/master/docker-compose.yml#L11) внутрь контейнера?

**Comment by Algorithm0** [comment]
> @Algorithm0запускается ли сервис через `go run ./cmd/main.go`? С последним коммитом подтянулась ли папка дб? Проверьте, прокидывает ли docker Compose [монтируемые папки](https://github.com/sku4/alice-checklist/blob/master/docker-compose.yml#L11) внутри контейнера?

Да, если я бегу `go run ./cmd/main.go`, то получаю:
```
pi@raspberrypi:~/Projects/alice-checklist $ go run ./cmd/main.go
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

{"level":"info","msg":"Checklist App Started","time":"2023-10-18T01:12:08+03:00"}
[GIN-debug] GET    /swagger/*any             --> github.com/swaggo/gin-swagger.CustomWrapHandler.func1 (1 handlers)
[GIN-debug] POST   /cmd/                     --> github.com/sku4/alice-checklist/internal/handler.(*Handler).aliceRequest-fm (1 handlers)
[GIN-debug] GET    /debug/pprof/             --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /debug/pprof/cmdline      --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /debug/pprof/profile      --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] POST   /debug/pprof/symbol       --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /debug/pprof/symbol       --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /debug/pprof/trace        --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /debug/pprof/allocs       --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /debug/pprof/block        --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /debug/pprof/goroutine    --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /debug/pprof/heap         --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /debug/pprof/mutex        --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /debug/pprof/threadcreate --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
^C{"level":"info","msg":"Checklist App Shutting Down","time":"2023-10-18T01:12:45+03:00"}
{"level":"fatal","msg":"error occured while running http server: http: Server closed","time":"2023-10-18T01:12:45+03:00"}
exit status 1
```

В принципе, я получаю такой же результат если не использовать docker-compose, а просто собираю образ и запускаю образ с монтированием нужных разделов по аналогии с тем, как Вы это делаете в правиле Makefile `start-container`.
Я не силен в docker-compose. Не знаю, как проверить монтируются ли данные папки. Но если `docker run` с монтированием делает тоже самое, то меня это устраивает.

**Comment by sku4** [comment]
> Но если docker run с монтированием делает тоже самое, то меня это устраивает.

По факту docker run делает тоже самое. 
Давайте,
